// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

/**
 * Patch resources are used to modify existing Kubernetes resources by using
 * Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
 * one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
 * Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
 * [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
 * additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
 * CiliumEndpointSlice contains a group of CoreCiliumendpoints.
 */
export class CiliumEndpointSlicePatch extends pulumi.CustomResource {
    /**
     * Get an existing CiliumEndpointSlicePatch resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CiliumEndpointSlicePatch {
        return new CiliumEndpointSlicePatch(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:cilium.io/v2alpha1:CiliumEndpointSlicePatch';

    /**
     * Returns true if the given object is an instance of CiliumEndpointSlicePatch.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CiliumEndpointSlicePatch {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CiliumEndpointSlicePatch.__pulumiType;
    }

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
    declare public readonly apiVersion: pulumi.Output<"cilium.io/v2alpha1">;
    /**
     * Endpoints is a list of coreCEPs packed in a CiliumEndpointSlice
     */
    declare public readonly endpoints: pulumi.Output<outputs.cilium.v2alpha1.CiliumEndpointSliceEndpointsPatch[]>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
    declare public readonly kind: pulumi.Output<"CiliumEndpointSlice">;
    /**
     * Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
     */
    declare public readonly metadata: pulumi.Output<outputs.meta.v1.ObjectMetaPatch>;
    /**
     * Namespace indicate as CiliumEndpointSlice namespace.
     * All the CiliumEndpoints within the same namespace are put together
     * in CiliumEndpointSlice.
     */
    declare public readonly namespace: pulumi.Output<string>;

    /**
     * Create a CiliumEndpointSlicePatch resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CiliumEndpointSlicePatchArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "cilium.io/v2alpha1";
            resourceInputs["endpoints"] = args?.endpoints;
            resourceInputs["kind"] = "CiliumEndpointSlice";
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["namespace"] = args?.namespace;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["endpoints"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CiliumEndpointSlicePatch.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CiliumEndpointSlicePatch resource.
 */
export interface CiliumEndpointSlicePatchArgs {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
    apiVersion?: pulumi.Input<"cilium.io/v2alpha1">;
    /**
     * Endpoints is a list of coreCEPs packed in a CiliumEndpointSlice
     */
    endpoints?: pulumi.Input<pulumi.Input<inputs.cilium.v2alpha1.CiliumEndpointSliceEndpointsPatch>[]>;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
    kind?: pulumi.Input<"CiliumEndpointSlice">;
    /**
     * Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
     */
    metadata?: pulumi.Input<inputs.meta.v1.ObjectMetaPatch>;
    /**
     * Namespace indicate as CiliumEndpointSlice namespace.
     * All the CiliumEndpoints within the same namespace are put together
     * in CiliumEndpointSlice.
     */
    namespace?: pulumi.Input<string>;
}
