// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { CiliumBGPAdvertisementArgs } from "./ciliumBGPAdvertisement";
export type CiliumBGPAdvertisement = import("./ciliumBGPAdvertisement").CiliumBGPAdvertisement;
export const CiliumBGPAdvertisement: typeof import("./ciliumBGPAdvertisement").CiliumBGPAdvertisement = null as any;
utilities.lazyLoad(exports, ["CiliumBGPAdvertisement"], () => require("./ciliumBGPAdvertisement"));

export { CiliumBGPAdvertisementListArgs } from "./ciliumBGPAdvertisementList";
export type CiliumBGPAdvertisementList = import("./ciliumBGPAdvertisementList").CiliumBGPAdvertisementList;
export const CiliumBGPAdvertisementList: typeof import("./ciliumBGPAdvertisementList").CiliumBGPAdvertisementList = null as any;
utilities.lazyLoad(exports, ["CiliumBGPAdvertisementList"], () => require("./ciliumBGPAdvertisementList"));

export { CiliumBGPAdvertisementPatchArgs } from "./ciliumBGPAdvertisementPatch";
export type CiliumBGPAdvertisementPatch = import("./ciliumBGPAdvertisementPatch").CiliumBGPAdvertisementPatch;
export const CiliumBGPAdvertisementPatch: typeof import("./ciliumBGPAdvertisementPatch").CiliumBGPAdvertisementPatch = null as any;
utilities.lazyLoad(exports, ["CiliumBGPAdvertisementPatch"], () => require("./ciliumBGPAdvertisementPatch"));

export { CiliumBGPClusterConfigArgs } from "./ciliumBGPClusterConfig";
export type CiliumBGPClusterConfig = import("./ciliumBGPClusterConfig").CiliumBGPClusterConfig;
export const CiliumBGPClusterConfig: typeof import("./ciliumBGPClusterConfig").CiliumBGPClusterConfig = null as any;
utilities.lazyLoad(exports, ["CiliumBGPClusterConfig"], () => require("./ciliumBGPClusterConfig"));

export { CiliumBGPClusterConfigListArgs } from "./ciliumBGPClusterConfigList";
export type CiliumBGPClusterConfigList = import("./ciliumBGPClusterConfigList").CiliumBGPClusterConfigList;
export const CiliumBGPClusterConfigList: typeof import("./ciliumBGPClusterConfigList").CiliumBGPClusterConfigList = null as any;
utilities.lazyLoad(exports, ["CiliumBGPClusterConfigList"], () => require("./ciliumBGPClusterConfigList"));

export { CiliumBGPClusterConfigPatchArgs } from "./ciliumBGPClusterConfigPatch";
export type CiliumBGPClusterConfigPatch = import("./ciliumBGPClusterConfigPatch").CiliumBGPClusterConfigPatch;
export const CiliumBGPClusterConfigPatch: typeof import("./ciliumBGPClusterConfigPatch").CiliumBGPClusterConfigPatch = null as any;
utilities.lazyLoad(exports, ["CiliumBGPClusterConfigPatch"], () => require("./ciliumBGPClusterConfigPatch"));

export { CiliumBGPNodeConfigArgs } from "./ciliumBGPNodeConfig";
export type CiliumBGPNodeConfig = import("./ciliumBGPNodeConfig").CiliumBGPNodeConfig;
export const CiliumBGPNodeConfig: typeof import("./ciliumBGPNodeConfig").CiliumBGPNodeConfig = null as any;
utilities.lazyLoad(exports, ["CiliumBGPNodeConfig"], () => require("./ciliumBGPNodeConfig"));

export { CiliumBGPNodeConfigListArgs } from "./ciliumBGPNodeConfigList";
export type CiliumBGPNodeConfigList = import("./ciliumBGPNodeConfigList").CiliumBGPNodeConfigList;
export const CiliumBGPNodeConfigList: typeof import("./ciliumBGPNodeConfigList").CiliumBGPNodeConfigList = null as any;
utilities.lazyLoad(exports, ["CiliumBGPNodeConfigList"], () => require("./ciliumBGPNodeConfigList"));

export { CiliumBGPNodeConfigOverrideArgs } from "./ciliumBGPNodeConfigOverride";
export type CiliumBGPNodeConfigOverride = import("./ciliumBGPNodeConfigOverride").CiliumBGPNodeConfigOverride;
export const CiliumBGPNodeConfigOverride: typeof import("./ciliumBGPNodeConfigOverride").CiliumBGPNodeConfigOverride = null as any;
utilities.lazyLoad(exports, ["CiliumBGPNodeConfigOverride"], () => require("./ciliumBGPNodeConfigOverride"));

export { CiliumBGPNodeConfigOverrideListArgs } from "./ciliumBGPNodeConfigOverrideList";
export type CiliumBGPNodeConfigOverrideList = import("./ciliumBGPNodeConfigOverrideList").CiliumBGPNodeConfigOverrideList;
export const CiliumBGPNodeConfigOverrideList: typeof import("./ciliumBGPNodeConfigOverrideList").CiliumBGPNodeConfigOverrideList = null as any;
utilities.lazyLoad(exports, ["CiliumBGPNodeConfigOverrideList"], () => require("./ciliumBGPNodeConfigOverrideList"));

export { CiliumBGPNodeConfigOverridePatchArgs } from "./ciliumBGPNodeConfigOverridePatch";
export type CiliumBGPNodeConfigOverridePatch = import("./ciliumBGPNodeConfigOverridePatch").CiliumBGPNodeConfigOverridePatch;
export const CiliumBGPNodeConfigOverridePatch: typeof import("./ciliumBGPNodeConfigOverridePatch").CiliumBGPNodeConfigOverridePatch = null as any;
utilities.lazyLoad(exports, ["CiliumBGPNodeConfigOverridePatch"], () => require("./ciliumBGPNodeConfigOverridePatch"));

export { CiliumBGPNodeConfigPatchArgs } from "./ciliumBGPNodeConfigPatch";
export type CiliumBGPNodeConfigPatch = import("./ciliumBGPNodeConfigPatch").CiliumBGPNodeConfigPatch;
export const CiliumBGPNodeConfigPatch: typeof import("./ciliumBGPNodeConfigPatch").CiliumBGPNodeConfigPatch = null as any;
utilities.lazyLoad(exports, ["CiliumBGPNodeConfigPatch"], () => require("./ciliumBGPNodeConfigPatch"));

export { CiliumBGPPeerConfigArgs } from "./ciliumBGPPeerConfig";
export type CiliumBGPPeerConfig = import("./ciliumBGPPeerConfig").CiliumBGPPeerConfig;
export const CiliumBGPPeerConfig: typeof import("./ciliumBGPPeerConfig").CiliumBGPPeerConfig = null as any;
utilities.lazyLoad(exports, ["CiliumBGPPeerConfig"], () => require("./ciliumBGPPeerConfig"));

export { CiliumBGPPeerConfigListArgs } from "./ciliumBGPPeerConfigList";
export type CiliumBGPPeerConfigList = import("./ciliumBGPPeerConfigList").CiliumBGPPeerConfigList;
export const CiliumBGPPeerConfigList: typeof import("./ciliumBGPPeerConfigList").CiliumBGPPeerConfigList = null as any;
utilities.lazyLoad(exports, ["CiliumBGPPeerConfigList"], () => require("./ciliumBGPPeerConfigList"));

export { CiliumBGPPeerConfigPatchArgs } from "./ciliumBGPPeerConfigPatch";
export type CiliumBGPPeerConfigPatch = import("./ciliumBGPPeerConfigPatch").CiliumBGPPeerConfigPatch;
export const CiliumBGPPeerConfigPatch: typeof import("./ciliumBGPPeerConfigPatch").CiliumBGPPeerConfigPatch = null as any;
utilities.lazyLoad(exports, ["CiliumBGPPeerConfigPatch"], () => require("./ciliumBGPPeerConfigPatch"));

export { CiliumBGPPeeringPolicyArgs } from "./ciliumBGPPeeringPolicy";
export type CiliumBGPPeeringPolicy = import("./ciliumBGPPeeringPolicy").CiliumBGPPeeringPolicy;
export const CiliumBGPPeeringPolicy: typeof import("./ciliumBGPPeeringPolicy").CiliumBGPPeeringPolicy = null as any;
utilities.lazyLoad(exports, ["CiliumBGPPeeringPolicy"], () => require("./ciliumBGPPeeringPolicy"));

export { CiliumBGPPeeringPolicyListArgs } from "./ciliumBGPPeeringPolicyList";
export type CiliumBGPPeeringPolicyList = import("./ciliumBGPPeeringPolicyList").CiliumBGPPeeringPolicyList;
export const CiliumBGPPeeringPolicyList: typeof import("./ciliumBGPPeeringPolicyList").CiliumBGPPeeringPolicyList = null as any;
utilities.lazyLoad(exports, ["CiliumBGPPeeringPolicyList"], () => require("./ciliumBGPPeeringPolicyList"));

export { CiliumBGPPeeringPolicyPatchArgs } from "./ciliumBGPPeeringPolicyPatch";
export type CiliumBGPPeeringPolicyPatch = import("./ciliumBGPPeeringPolicyPatch").CiliumBGPPeeringPolicyPatch;
export const CiliumBGPPeeringPolicyPatch: typeof import("./ciliumBGPPeeringPolicyPatch").CiliumBGPPeeringPolicyPatch = null as any;
utilities.lazyLoad(exports, ["CiliumBGPPeeringPolicyPatch"], () => require("./ciliumBGPPeeringPolicyPatch"));

export { CiliumCIDRGroupArgs } from "./ciliumCIDRGroup";
export type CiliumCIDRGroup = import("./ciliumCIDRGroup").CiliumCIDRGroup;
export const CiliumCIDRGroup: typeof import("./ciliumCIDRGroup").CiliumCIDRGroup = null as any;
utilities.lazyLoad(exports, ["CiliumCIDRGroup"], () => require("./ciliumCIDRGroup"));

export { CiliumCIDRGroupListArgs } from "./ciliumCIDRGroupList";
export type CiliumCIDRGroupList = import("./ciliumCIDRGroupList").CiliumCIDRGroupList;
export const CiliumCIDRGroupList: typeof import("./ciliumCIDRGroupList").CiliumCIDRGroupList = null as any;
utilities.lazyLoad(exports, ["CiliumCIDRGroupList"], () => require("./ciliumCIDRGroupList"));

export { CiliumCIDRGroupPatchArgs } from "./ciliumCIDRGroupPatch";
export type CiliumCIDRGroupPatch = import("./ciliumCIDRGroupPatch").CiliumCIDRGroupPatch;
export const CiliumCIDRGroupPatch: typeof import("./ciliumCIDRGroupPatch").CiliumCIDRGroupPatch = null as any;
utilities.lazyLoad(exports, ["CiliumCIDRGroupPatch"], () => require("./ciliumCIDRGroupPatch"));

export { CiliumEndpointSliceArgs } from "./ciliumEndpointSlice";
export type CiliumEndpointSlice = import("./ciliumEndpointSlice").CiliumEndpointSlice;
export const CiliumEndpointSlice: typeof import("./ciliumEndpointSlice").CiliumEndpointSlice = null as any;
utilities.lazyLoad(exports, ["CiliumEndpointSlice"], () => require("./ciliumEndpointSlice"));

export { CiliumEndpointSliceListArgs } from "./ciliumEndpointSliceList";
export type CiliumEndpointSliceList = import("./ciliumEndpointSliceList").CiliumEndpointSliceList;
export const CiliumEndpointSliceList: typeof import("./ciliumEndpointSliceList").CiliumEndpointSliceList = null as any;
utilities.lazyLoad(exports, ["CiliumEndpointSliceList"], () => require("./ciliumEndpointSliceList"));

export { CiliumEndpointSlicePatchArgs } from "./ciliumEndpointSlicePatch";
export type CiliumEndpointSlicePatch = import("./ciliumEndpointSlicePatch").CiliumEndpointSlicePatch;
export const CiliumEndpointSlicePatch: typeof import("./ciliumEndpointSlicePatch").CiliumEndpointSlicePatch = null as any;
utilities.lazyLoad(exports, ["CiliumEndpointSlicePatch"], () => require("./ciliumEndpointSlicePatch"));

export { CiliumL2AnnouncementPolicyArgs } from "./ciliumL2AnnouncementPolicy";
export type CiliumL2AnnouncementPolicy = import("./ciliumL2AnnouncementPolicy").CiliumL2AnnouncementPolicy;
export const CiliumL2AnnouncementPolicy: typeof import("./ciliumL2AnnouncementPolicy").CiliumL2AnnouncementPolicy = null as any;
utilities.lazyLoad(exports, ["CiliumL2AnnouncementPolicy"], () => require("./ciliumL2AnnouncementPolicy"));

export { CiliumL2AnnouncementPolicyListArgs } from "./ciliumL2AnnouncementPolicyList";
export type CiliumL2AnnouncementPolicyList = import("./ciliumL2AnnouncementPolicyList").CiliumL2AnnouncementPolicyList;
export const CiliumL2AnnouncementPolicyList: typeof import("./ciliumL2AnnouncementPolicyList").CiliumL2AnnouncementPolicyList = null as any;
utilities.lazyLoad(exports, ["CiliumL2AnnouncementPolicyList"], () => require("./ciliumL2AnnouncementPolicyList"));

export { CiliumL2AnnouncementPolicyPatchArgs } from "./ciliumL2AnnouncementPolicyPatch";
export type CiliumL2AnnouncementPolicyPatch = import("./ciliumL2AnnouncementPolicyPatch").CiliumL2AnnouncementPolicyPatch;
export const CiliumL2AnnouncementPolicyPatch: typeof import("./ciliumL2AnnouncementPolicyPatch").CiliumL2AnnouncementPolicyPatch = null as any;
utilities.lazyLoad(exports, ["CiliumL2AnnouncementPolicyPatch"], () => require("./ciliumL2AnnouncementPolicyPatch"));

export { CiliumLoadBalancerIPPoolArgs } from "./ciliumLoadBalancerIPPool";
export type CiliumLoadBalancerIPPool = import("./ciliumLoadBalancerIPPool").CiliumLoadBalancerIPPool;
export const CiliumLoadBalancerIPPool: typeof import("./ciliumLoadBalancerIPPool").CiliumLoadBalancerIPPool = null as any;
utilities.lazyLoad(exports, ["CiliumLoadBalancerIPPool"], () => require("./ciliumLoadBalancerIPPool"));

export { CiliumLoadBalancerIPPoolListArgs } from "./ciliumLoadBalancerIPPoolList";
export type CiliumLoadBalancerIPPoolList = import("./ciliumLoadBalancerIPPoolList").CiliumLoadBalancerIPPoolList;
export const CiliumLoadBalancerIPPoolList: typeof import("./ciliumLoadBalancerIPPoolList").CiliumLoadBalancerIPPoolList = null as any;
utilities.lazyLoad(exports, ["CiliumLoadBalancerIPPoolList"], () => require("./ciliumLoadBalancerIPPoolList"));

export { CiliumLoadBalancerIPPoolPatchArgs } from "./ciliumLoadBalancerIPPoolPatch";
export type CiliumLoadBalancerIPPoolPatch = import("./ciliumLoadBalancerIPPoolPatch").CiliumLoadBalancerIPPoolPatch;
export const CiliumLoadBalancerIPPoolPatch: typeof import("./ciliumLoadBalancerIPPoolPatch").CiliumLoadBalancerIPPoolPatch = null as any;
utilities.lazyLoad(exports, ["CiliumLoadBalancerIPPoolPatch"], () => require("./ciliumLoadBalancerIPPoolPatch"));

export { CiliumNodeConfigArgs } from "./ciliumNodeConfig";
export type CiliumNodeConfig = import("./ciliumNodeConfig").CiliumNodeConfig;
export const CiliumNodeConfig: typeof import("./ciliumNodeConfig").CiliumNodeConfig = null as any;
utilities.lazyLoad(exports, ["CiliumNodeConfig"], () => require("./ciliumNodeConfig"));

export { CiliumNodeConfigListArgs } from "./ciliumNodeConfigList";
export type CiliumNodeConfigList = import("./ciliumNodeConfigList").CiliumNodeConfigList;
export const CiliumNodeConfigList: typeof import("./ciliumNodeConfigList").CiliumNodeConfigList = null as any;
utilities.lazyLoad(exports, ["CiliumNodeConfigList"], () => require("./ciliumNodeConfigList"));

export { CiliumNodeConfigPatchArgs } from "./ciliumNodeConfigPatch";
export type CiliumNodeConfigPatch = import("./ciliumNodeConfigPatch").CiliumNodeConfigPatch;
export const CiliumNodeConfigPatch: typeof import("./ciliumNodeConfigPatch").CiliumNodeConfigPatch = null as any;
utilities.lazyLoad(exports, ["CiliumNodeConfigPatch"], () => require("./ciliumNodeConfigPatch"));

export { CiliumPodIPPoolArgs } from "./ciliumPodIPPool";
export type CiliumPodIPPool = import("./ciliumPodIPPool").CiliumPodIPPool;
export const CiliumPodIPPool: typeof import("./ciliumPodIPPool").CiliumPodIPPool = null as any;
utilities.lazyLoad(exports, ["CiliumPodIPPool"], () => require("./ciliumPodIPPool"));

export { CiliumPodIPPoolListArgs } from "./ciliumPodIPPoolList";
export type CiliumPodIPPoolList = import("./ciliumPodIPPoolList").CiliumPodIPPoolList;
export const CiliumPodIPPoolList: typeof import("./ciliumPodIPPoolList").CiliumPodIPPoolList = null as any;
utilities.lazyLoad(exports, ["CiliumPodIPPoolList"], () => require("./ciliumPodIPPoolList"));

export { CiliumPodIPPoolPatchArgs } from "./ciliumPodIPPoolPatch";
export type CiliumPodIPPoolPatch = import("./ciliumPodIPPoolPatch").CiliumPodIPPoolPatch;
export const CiliumPodIPPoolPatch: typeof import("./ciliumPodIPPoolPatch").CiliumPodIPPoolPatch = null as any;
utilities.lazyLoad(exports, ["CiliumPodIPPoolPatch"], () => require("./ciliumPodIPPoolPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPAdvertisement":
                return new CiliumBGPAdvertisement(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPAdvertisementList":
                return new CiliumBGPAdvertisementList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPAdvertisementPatch":
                return new CiliumBGPAdvertisementPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPClusterConfig":
                return new CiliumBGPClusterConfig(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPClusterConfigList":
                return new CiliumBGPClusterConfigList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPClusterConfigPatch":
                return new CiliumBGPClusterConfigPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPNodeConfig":
                return new CiliumBGPNodeConfig(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPNodeConfigList":
                return new CiliumBGPNodeConfigList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPNodeConfigOverride":
                return new CiliumBGPNodeConfigOverride(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPNodeConfigOverrideList":
                return new CiliumBGPNodeConfigOverrideList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPNodeConfigOverridePatch":
                return new CiliumBGPNodeConfigOverridePatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPNodeConfigPatch":
                return new CiliumBGPNodeConfigPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPPeerConfig":
                return new CiliumBGPPeerConfig(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPPeerConfigList":
                return new CiliumBGPPeerConfigList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPPeerConfigPatch":
                return new CiliumBGPPeerConfigPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPPeeringPolicy":
                return new CiliumBGPPeeringPolicy(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPPeeringPolicyList":
                return new CiliumBGPPeeringPolicyList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumBGPPeeringPolicyPatch":
                return new CiliumBGPPeeringPolicyPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumCIDRGroup":
                return new CiliumCIDRGroup(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumCIDRGroupList":
                return new CiliumCIDRGroupList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumCIDRGroupPatch":
                return new CiliumCIDRGroupPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumEndpointSlice":
                return new CiliumEndpointSlice(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumEndpointSliceList":
                return new CiliumEndpointSliceList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumEndpointSlicePatch":
                return new CiliumEndpointSlicePatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumL2AnnouncementPolicy":
                return new CiliumL2AnnouncementPolicy(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumL2AnnouncementPolicyList":
                return new CiliumL2AnnouncementPolicyList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumL2AnnouncementPolicyPatch":
                return new CiliumL2AnnouncementPolicyPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumLoadBalancerIPPool":
                return new CiliumLoadBalancerIPPool(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumLoadBalancerIPPoolList":
                return new CiliumLoadBalancerIPPoolList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumLoadBalancerIPPoolPatch":
                return new CiliumLoadBalancerIPPoolPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumNodeConfig":
                return new CiliumNodeConfig(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumNodeConfigList":
                return new CiliumNodeConfigList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumNodeConfigPatch":
                return new CiliumNodeConfigPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumPodIPPool":
                return new CiliumPodIPPool(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumPodIPPoolList":
                return new CiliumPodIPPoolList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2alpha1:CiliumPodIPPoolPatch":
                return new CiliumPodIPPoolPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "cilium.io/v2alpha1", _module)
