import "./namespaces.ts";
import "./cilium-bgp.ts";
import "./istio.ts";
import "./gateway-api.ts";
import "./cert-manager.ts";
import "./topolvm.ts";
import "./rook-ceph.ts";
import "./external-dns.ts";
import "./ingress-gateway.ts";
