// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

/**
 * Patch resources are used to modify existing Kubernetes resources by using
 * Server-Side Apply updates. The name of the resource must be specified, but all other properties are optional. More than
 * one patch may be applied to the same resource, and a random FieldManager name will be used for each Patch resource.
 * Conflicts will result in an error by default, but can be forced using the "pulumi.com/patchForce" annotation. See the
 * [Server-Side Apply Docs](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/) for
 * additional information about using Server-Side Apply to manage Kubernetes resources with Pulumi.
 * CiliumExternalWorkload is a Kubernetes Custom Resource that
 * contains a specification for an external workload that can join the
 * cluster.  The name of the CRD is the FQDN of the external workload,
 * and it needs to match the name in the workload registration. The
 * labels on the CRD object are the labels that will be used to
 * allocate a Cilium Identity for the external workload. If
 * 'io.kubernetes.pod.namespace' or 'io.kubernetes.pod.name' labels
 * are not explicitly specified, they will be defaulted to 'default'
 * and <workload name>, respectively. 'io.cilium.k8s.policy.cluster'
 * will always be defined as the name of the current cluster, which
 * defaults to "default".
 */
export class CiliumExternalWorkloadPatch extends pulumi.CustomResource {
    /**
     * Get an existing CiliumExternalWorkloadPatch resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CiliumExternalWorkloadPatch {
        return new CiliumExternalWorkloadPatch(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:cilium.io/v2:CiliumExternalWorkloadPatch';

    /**
     * Returns true if the given object is an instance of CiliumExternalWorkloadPatch.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CiliumExternalWorkloadPatch {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CiliumExternalWorkloadPatch.__pulumiType;
    }

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
    declare public readonly apiVersion: pulumi.Output<"cilium.io/v2">;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
    declare public readonly kind: pulumi.Output<"CiliumExternalWorkload">;
    /**
     * Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
     */
    declare public readonly metadata: pulumi.Output<outputs.meta.v1.ObjectMetaPatch>;
    declare public readonly spec: pulumi.Output<outputs.cilium.v2.CiliumExternalWorkloadSpecPatch>;
    declare public /*out*/ readonly status: pulumi.Output<outputs.cilium.v2.CiliumExternalWorkloadStatusPatch>;

    /**
     * Create a CiliumExternalWorkloadPatch resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CiliumExternalWorkloadPatchArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "cilium.io/v2";
            resourceInputs["kind"] = "CiliumExternalWorkload";
            resourceInputs["metadata"] = args?.metadata;
            resourceInputs["spec"] = args?.spec;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CiliumExternalWorkloadPatch.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CiliumExternalWorkloadPatch resource.
 */
export interface CiliumExternalWorkloadPatchArgs {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     */
    apiVersion?: pulumi.Input<"cilium.io/v2">;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     */
    kind?: pulumi.Input<"CiliumExternalWorkload">;
    /**
     * Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
     */
    metadata?: pulumi.Input<inputs.meta.v1.ObjectMetaPatch>;
    spec?: pulumi.Input<inputs.cilium.v2.CiliumExternalWorkloadSpecPatch>;
}
