apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: egoavara-net
image: rancher/k3s:v1.30.3-k3s1
kubeAPI:
  host: "kubernetes.egoavara.net"
  hostIP: "0.0.0.0"
  hostPort: "6443"
ports:
  - port: "80:80"
    nodeFilters:
      - loadbalancer
  - port: "443:443"
    nodeFilters:
      - loadbalancer
servers: 3
agents: 3
network: k3d-egoavara-net
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
  k3s: 
    extraArgs:
      - arg: --tls-san=kubernetes.egoavara.net
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*