// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { CiliumClusterwideEnvoyConfigArgs } from "./ciliumClusterwideEnvoyConfig";
export type CiliumClusterwideEnvoyConfig = import("./ciliumClusterwideEnvoyConfig").CiliumClusterwideEnvoyConfig;
export const CiliumClusterwideEnvoyConfig: typeof import("./ciliumClusterwideEnvoyConfig").CiliumClusterwideEnvoyConfig = null as any;
utilities.lazyLoad(exports, ["CiliumClusterwideEnvoyConfig"], () => require("./ciliumClusterwideEnvoyConfig"));

export { CiliumClusterwideEnvoyConfigListArgs } from "./ciliumClusterwideEnvoyConfigList";
export type CiliumClusterwideEnvoyConfigList = import("./ciliumClusterwideEnvoyConfigList").CiliumClusterwideEnvoyConfigList;
export const CiliumClusterwideEnvoyConfigList: typeof import("./ciliumClusterwideEnvoyConfigList").CiliumClusterwideEnvoyConfigList = null as any;
utilities.lazyLoad(exports, ["CiliumClusterwideEnvoyConfigList"], () => require("./ciliumClusterwideEnvoyConfigList"));

export { CiliumClusterwideEnvoyConfigPatchArgs } from "./ciliumClusterwideEnvoyConfigPatch";
export type CiliumClusterwideEnvoyConfigPatch = import("./ciliumClusterwideEnvoyConfigPatch").CiliumClusterwideEnvoyConfigPatch;
export const CiliumClusterwideEnvoyConfigPatch: typeof import("./ciliumClusterwideEnvoyConfigPatch").CiliumClusterwideEnvoyConfigPatch = null as any;
utilities.lazyLoad(exports, ["CiliumClusterwideEnvoyConfigPatch"], () => require("./ciliumClusterwideEnvoyConfigPatch"));

export { CiliumClusterwideNetworkPolicyArgs } from "./ciliumClusterwideNetworkPolicy";
export type CiliumClusterwideNetworkPolicy = import("./ciliumClusterwideNetworkPolicy").CiliumClusterwideNetworkPolicy;
export const CiliumClusterwideNetworkPolicy: typeof import("./ciliumClusterwideNetworkPolicy").CiliumClusterwideNetworkPolicy = null as any;
utilities.lazyLoad(exports, ["CiliumClusterwideNetworkPolicy"], () => require("./ciliumClusterwideNetworkPolicy"));

export { CiliumClusterwideNetworkPolicyListArgs } from "./ciliumClusterwideNetworkPolicyList";
export type CiliumClusterwideNetworkPolicyList = import("./ciliumClusterwideNetworkPolicyList").CiliumClusterwideNetworkPolicyList;
export const CiliumClusterwideNetworkPolicyList: typeof import("./ciliumClusterwideNetworkPolicyList").CiliumClusterwideNetworkPolicyList = null as any;
utilities.lazyLoad(exports, ["CiliumClusterwideNetworkPolicyList"], () => require("./ciliumClusterwideNetworkPolicyList"));

export { CiliumClusterwideNetworkPolicyPatchArgs } from "./ciliumClusterwideNetworkPolicyPatch";
export type CiliumClusterwideNetworkPolicyPatch = import("./ciliumClusterwideNetworkPolicyPatch").CiliumClusterwideNetworkPolicyPatch;
export const CiliumClusterwideNetworkPolicyPatch: typeof import("./ciliumClusterwideNetworkPolicyPatch").CiliumClusterwideNetworkPolicyPatch = null as any;
utilities.lazyLoad(exports, ["CiliumClusterwideNetworkPolicyPatch"], () => require("./ciliumClusterwideNetworkPolicyPatch"));

export { CiliumEgressGatewayPolicyArgs } from "./ciliumEgressGatewayPolicy";
export type CiliumEgressGatewayPolicy = import("./ciliumEgressGatewayPolicy").CiliumEgressGatewayPolicy;
export const CiliumEgressGatewayPolicy: typeof import("./ciliumEgressGatewayPolicy").CiliumEgressGatewayPolicy = null as any;
utilities.lazyLoad(exports, ["CiliumEgressGatewayPolicy"], () => require("./ciliumEgressGatewayPolicy"));

export { CiliumEgressGatewayPolicyListArgs } from "./ciliumEgressGatewayPolicyList";
export type CiliumEgressGatewayPolicyList = import("./ciliumEgressGatewayPolicyList").CiliumEgressGatewayPolicyList;
export const CiliumEgressGatewayPolicyList: typeof import("./ciliumEgressGatewayPolicyList").CiliumEgressGatewayPolicyList = null as any;
utilities.lazyLoad(exports, ["CiliumEgressGatewayPolicyList"], () => require("./ciliumEgressGatewayPolicyList"));

export { CiliumEgressGatewayPolicyPatchArgs } from "./ciliumEgressGatewayPolicyPatch";
export type CiliumEgressGatewayPolicyPatch = import("./ciliumEgressGatewayPolicyPatch").CiliumEgressGatewayPolicyPatch;
export const CiliumEgressGatewayPolicyPatch: typeof import("./ciliumEgressGatewayPolicyPatch").CiliumEgressGatewayPolicyPatch = null as any;
utilities.lazyLoad(exports, ["CiliumEgressGatewayPolicyPatch"], () => require("./ciliumEgressGatewayPolicyPatch"));

export { CiliumEndpointArgs } from "./ciliumEndpoint";
export type CiliumEndpoint = import("./ciliumEndpoint").CiliumEndpoint;
export const CiliumEndpoint: typeof import("./ciliumEndpoint").CiliumEndpoint = null as any;
utilities.lazyLoad(exports, ["CiliumEndpoint"], () => require("./ciliumEndpoint"));

export { CiliumEndpointListArgs } from "./ciliumEndpointList";
export type CiliumEndpointList = import("./ciliumEndpointList").CiliumEndpointList;
export const CiliumEndpointList: typeof import("./ciliumEndpointList").CiliumEndpointList = null as any;
utilities.lazyLoad(exports, ["CiliumEndpointList"], () => require("./ciliumEndpointList"));

export { CiliumEndpointPatchArgs } from "./ciliumEndpointPatch";
export type CiliumEndpointPatch = import("./ciliumEndpointPatch").CiliumEndpointPatch;
export const CiliumEndpointPatch: typeof import("./ciliumEndpointPatch").CiliumEndpointPatch = null as any;
utilities.lazyLoad(exports, ["CiliumEndpointPatch"], () => require("./ciliumEndpointPatch"));

export { CiliumEnvoyConfigArgs } from "./ciliumEnvoyConfig";
export type CiliumEnvoyConfig = import("./ciliumEnvoyConfig").CiliumEnvoyConfig;
export const CiliumEnvoyConfig: typeof import("./ciliumEnvoyConfig").CiliumEnvoyConfig = null as any;
utilities.lazyLoad(exports, ["CiliumEnvoyConfig"], () => require("./ciliumEnvoyConfig"));

export { CiliumEnvoyConfigListArgs } from "./ciliumEnvoyConfigList";
export type CiliumEnvoyConfigList = import("./ciliumEnvoyConfigList").CiliumEnvoyConfigList;
export const CiliumEnvoyConfigList: typeof import("./ciliumEnvoyConfigList").CiliumEnvoyConfigList = null as any;
utilities.lazyLoad(exports, ["CiliumEnvoyConfigList"], () => require("./ciliumEnvoyConfigList"));

export { CiliumEnvoyConfigPatchArgs } from "./ciliumEnvoyConfigPatch";
export type CiliumEnvoyConfigPatch = import("./ciliumEnvoyConfigPatch").CiliumEnvoyConfigPatch;
export const CiliumEnvoyConfigPatch: typeof import("./ciliumEnvoyConfigPatch").CiliumEnvoyConfigPatch = null as any;
utilities.lazyLoad(exports, ["CiliumEnvoyConfigPatch"], () => require("./ciliumEnvoyConfigPatch"));

export { CiliumExternalWorkloadArgs } from "./ciliumExternalWorkload";
export type CiliumExternalWorkload = import("./ciliumExternalWorkload").CiliumExternalWorkload;
export const CiliumExternalWorkload: typeof import("./ciliumExternalWorkload").CiliumExternalWorkload = null as any;
utilities.lazyLoad(exports, ["CiliumExternalWorkload"], () => require("./ciliumExternalWorkload"));

export { CiliumExternalWorkloadListArgs } from "./ciliumExternalWorkloadList";
export type CiliumExternalWorkloadList = import("./ciliumExternalWorkloadList").CiliumExternalWorkloadList;
export const CiliumExternalWorkloadList: typeof import("./ciliumExternalWorkloadList").CiliumExternalWorkloadList = null as any;
utilities.lazyLoad(exports, ["CiliumExternalWorkloadList"], () => require("./ciliumExternalWorkloadList"));

export { CiliumExternalWorkloadPatchArgs } from "./ciliumExternalWorkloadPatch";
export type CiliumExternalWorkloadPatch = import("./ciliumExternalWorkloadPatch").CiliumExternalWorkloadPatch;
export const CiliumExternalWorkloadPatch: typeof import("./ciliumExternalWorkloadPatch").CiliumExternalWorkloadPatch = null as any;
utilities.lazyLoad(exports, ["CiliumExternalWorkloadPatch"], () => require("./ciliumExternalWorkloadPatch"));

export { CiliumIdentityArgs } from "./ciliumIdentity";
export type CiliumIdentity = import("./ciliumIdentity").CiliumIdentity;
export const CiliumIdentity: typeof import("./ciliumIdentity").CiliumIdentity = null as any;
utilities.lazyLoad(exports, ["CiliumIdentity"], () => require("./ciliumIdentity"));

export { CiliumIdentityListArgs } from "./ciliumIdentityList";
export type CiliumIdentityList = import("./ciliumIdentityList").CiliumIdentityList;
export const CiliumIdentityList: typeof import("./ciliumIdentityList").CiliumIdentityList = null as any;
utilities.lazyLoad(exports, ["CiliumIdentityList"], () => require("./ciliumIdentityList"));

export { CiliumIdentityPatchArgs } from "./ciliumIdentityPatch";
export type CiliumIdentityPatch = import("./ciliumIdentityPatch").CiliumIdentityPatch;
export const CiliumIdentityPatch: typeof import("./ciliumIdentityPatch").CiliumIdentityPatch = null as any;
utilities.lazyLoad(exports, ["CiliumIdentityPatch"], () => require("./ciliumIdentityPatch"));

export { CiliumLocalRedirectPolicyArgs } from "./ciliumLocalRedirectPolicy";
export type CiliumLocalRedirectPolicy = import("./ciliumLocalRedirectPolicy").CiliumLocalRedirectPolicy;
export const CiliumLocalRedirectPolicy: typeof import("./ciliumLocalRedirectPolicy").CiliumLocalRedirectPolicy = null as any;
utilities.lazyLoad(exports, ["CiliumLocalRedirectPolicy"], () => require("./ciliumLocalRedirectPolicy"));

export { CiliumLocalRedirectPolicyListArgs } from "./ciliumLocalRedirectPolicyList";
export type CiliumLocalRedirectPolicyList = import("./ciliumLocalRedirectPolicyList").CiliumLocalRedirectPolicyList;
export const CiliumLocalRedirectPolicyList: typeof import("./ciliumLocalRedirectPolicyList").CiliumLocalRedirectPolicyList = null as any;
utilities.lazyLoad(exports, ["CiliumLocalRedirectPolicyList"], () => require("./ciliumLocalRedirectPolicyList"));

export { CiliumLocalRedirectPolicyPatchArgs } from "./ciliumLocalRedirectPolicyPatch";
export type CiliumLocalRedirectPolicyPatch = import("./ciliumLocalRedirectPolicyPatch").CiliumLocalRedirectPolicyPatch;
export const CiliumLocalRedirectPolicyPatch: typeof import("./ciliumLocalRedirectPolicyPatch").CiliumLocalRedirectPolicyPatch = null as any;
utilities.lazyLoad(exports, ["CiliumLocalRedirectPolicyPatch"], () => require("./ciliumLocalRedirectPolicyPatch"));

export { CiliumNetworkPolicyArgs } from "./ciliumNetworkPolicy";
export type CiliumNetworkPolicy = import("./ciliumNetworkPolicy").CiliumNetworkPolicy;
export const CiliumNetworkPolicy: typeof import("./ciliumNetworkPolicy").CiliumNetworkPolicy = null as any;
utilities.lazyLoad(exports, ["CiliumNetworkPolicy"], () => require("./ciliumNetworkPolicy"));

export { CiliumNetworkPolicyListArgs } from "./ciliumNetworkPolicyList";
export type CiliumNetworkPolicyList = import("./ciliumNetworkPolicyList").CiliumNetworkPolicyList;
export const CiliumNetworkPolicyList: typeof import("./ciliumNetworkPolicyList").CiliumNetworkPolicyList = null as any;
utilities.lazyLoad(exports, ["CiliumNetworkPolicyList"], () => require("./ciliumNetworkPolicyList"));

export { CiliumNetworkPolicyPatchArgs } from "./ciliumNetworkPolicyPatch";
export type CiliumNetworkPolicyPatch = import("./ciliumNetworkPolicyPatch").CiliumNetworkPolicyPatch;
export const CiliumNetworkPolicyPatch: typeof import("./ciliumNetworkPolicyPatch").CiliumNetworkPolicyPatch = null as any;
utilities.lazyLoad(exports, ["CiliumNetworkPolicyPatch"], () => require("./ciliumNetworkPolicyPatch"));

export { CiliumNodeArgs } from "./ciliumNode";
export type CiliumNode = import("./ciliumNode").CiliumNode;
export const CiliumNode: typeof import("./ciliumNode").CiliumNode = null as any;
utilities.lazyLoad(exports, ["CiliumNode"], () => require("./ciliumNode"));

export { CiliumNodeConfigArgs } from "./ciliumNodeConfig";
export type CiliumNodeConfig = import("./ciliumNodeConfig").CiliumNodeConfig;
export const CiliumNodeConfig: typeof import("./ciliumNodeConfig").CiliumNodeConfig = null as any;
utilities.lazyLoad(exports, ["CiliumNodeConfig"], () => require("./ciliumNodeConfig"));

export { CiliumNodeConfigListArgs } from "./ciliumNodeConfigList";
export type CiliumNodeConfigList = import("./ciliumNodeConfigList").CiliumNodeConfigList;
export const CiliumNodeConfigList: typeof import("./ciliumNodeConfigList").CiliumNodeConfigList = null as any;
utilities.lazyLoad(exports, ["CiliumNodeConfigList"], () => require("./ciliumNodeConfigList"));

export { CiliumNodeConfigPatchArgs } from "./ciliumNodeConfigPatch";
export type CiliumNodeConfigPatch = import("./ciliumNodeConfigPatch").CiliumNodeConfigPatch;
export const CiliumNodeConfigPatch: typeof import("./ciliumNodeConfigPatch").CiliumNodeConfigPatch = null as any;
utilities.lazyLoad(exports, ["CiliumNodeConfigPatch"], () => require("./ciliumNodeConfigPatch"));

export { CiliumNodeListArgs } from "./ciliumNodeList";
export type CiliumNodeList = import("./ciliumNodeList").CiliumNodeList;
export const CiliumNodeList: typeof import("./ciliumNodeList").CiliumNodeList = null as any;
utilities.lazyLoad(exports, ["CiliumNodeList"], () => require("./ciliumNodeList"));

export { CiliumNodePatchArgs } from "./ciliumNodePatch";
export type CiliumNodePatch = import("./ciliumNodePatch").CiliumNodePatch;
export const CiliumNodePatch: typeof import("./ciliumNodePatch").CiliumNodePatch = null as any;
utilities.lazyLoad(exports, ["CiliumNodePatch"], () => require("./ciliumNodePatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:cilium.io/v2:CiliumClusterwideEnvoyConfig":
                return new CiliumClusterwideEnvoyConfig(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumClusterwideEnvoyConfigList":
                return new CiliumClusterwideEnvoyConfigList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumClusterwideEnvoyConfigPatch":
                return new CiliumClusterwideEnvoyConfigPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumClusterwideNetworkPolicy":
                return new CiliumClusterwideNetworkPolicy(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumClusterwideNetworkPolicyList":
                return new CiliumClusterwideNetworkPolicyList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumClusterwideNetworkPolicyPatch":
                return new CiliumClusterwideNetworkPolicyPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumEgressGatewayPolicy":
                return new CiliumEgressGatewayPolicy(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumEgressGatewayPolicyList":
                return new CiliumEgressGatewayPolicyList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumEgressGatewayPolicyPatch":
                return new CiliumEgressGatewayPolicyPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumEndpoint":
                return new CiliumEndpoint(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumEndpointList":
                return new CiliumEndpointList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumEndpointPatch":
                return new CiliumEndpointPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumEnvoyConfig":
                return new CiliumEnvoyConfig(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumEnvoyConfigList":
                return new CiliumEnvoyConfigList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumEnvoyConfigPatch":
                return new CiliumEnvoyConfigPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumExternalWorkload":
                return new CiliumExternalWorkload(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumExternalWorkloadList":
                return new CiliumExternalWorkloadList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumExternalWorkloadPatch":
                return new CiliumExternalWorkloadPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumIdentity":
                return new CiliumIdentity(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumIdentityList":
                return new CiliumIdentityList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumIdentityPatch":
                return new CiliumIdentityPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumLocalRedirectPolicy":
                return new CiliumLocalRedirectPolicy(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumLocalRedirectPolicyList":
                return new CiliumLocalRedirectPolicyList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumLocalRedirectPolicyPatch":
                return new CiliumLocalRedirectPolicyPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumNetworkPolicy":
                return new CiliumNetworkPolicy(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumNetworkPolicyList":
                return new CiliumNetworkPolicyList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumNetworkPolicyPatch":
                return new CiliumNetworkPolicyPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumNode":
                return new CiliumNode(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumNodeConfig":
                return new CiliumNodeConfig(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumNodeConfigList":
                return new CiliumNodeConfigList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumNodeConfigPatch":
                return new CiliumNodeConfigPatch(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumNodeList":
                return new CiliumNodeList(name, <any>undefined, { urn })
            case "kubernetes:cilium.io/v2:CiliumNodePatch":
                return new CiliumNodePatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "cilium.io/v2", _module)
